### ISSUE TITLE
Error Codec incompatible

### ISSUE THREAD

**Issue by velvenkatesh** [sunnyqeen/sipdroid#2]
G729 could not be able to configured into our projects. G729 Codec method isValid() always returns false.
How to fix it?

**Comment by velvenkatesh** [comment]
**Error While using G729**



E/RtpStreamSender: setDTMFpayloadType101
W/Settings: Setting wifi_sleep_policy has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
E/AudioRecord: AudioFlinger could not create record track, status: -1
E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -1.
E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
I/Timeline: Timeline: Activity_launch_request time:20028080
W/Settings: Setting wifi_sleep_policy has moved from android.provider.Settings.System to android.provider.Settings.Global, value is unchanged.
E/art: No implementation found for void org.sipdroid.codecs.G729.close() (tried Java_org_sipdroid_codecs_G729_close and Java_org_sipdroid_codecs_G729_close__)
E/AndroidRuntime: FATAL EXCEPTION: Thread-2361
                  Process: org.sipdroid.sipua, PID: 15784
                  java.lang.UnsatisfiedLinkError: No implementation found for void org.sipdroid.codecs.G729.close() (tried Java_org_sipdroid_codecs_G729_close and Java_org_sipdroid_codecs_G729_close__)
                      at org.sipdroid.codecs.G729.close(Native Method)
                      at org.sipdroid.media.RtpStreamSender.run(RtpStreamSender.java:524)
W/Settings: Setting wifi_sleep_policy has moved from android.provider.Settings.System to android.provider.Settings.Global, value is unchanged.
E/art: No implementation found for void org.sipdroid.codecs.G729.close() (tried Java_org_sipdroid_codecs_G729_close and Java_org_sipdroid_codecs_G729_close__)
I/Process: Sending signal. PID: 15784 SIG: 9
Application terminated.

**Comment by velvenkatesh** [comment]
**

> G729 Encoder Error

**
E/RtpStreamSender: setDTMFpayloadType101
W/Settings: Setting wifi_sleep_policy has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
W/Settings: Setting wifi_sleep_policy has moved from android.provider.Settings.System to android.provider.Settings.Global, value is unchanged.
E/art: No implementation found for int org.sipdroid.codecs.G729.encode(short[], int, byte[], int) (tried Java_org_sipdroid_codecs_G729_encode and Java_org_sipdroid_codecs_G729_encode___3SI_3BI)

       --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: Thread-3953
                  Process: org.sipdroid.sipua, PID: 22138
                  java.lang.UnsatisfiedLinkError: No implementation found for int org.sipdroid.codecs.G729.encode(short[], int, byte[], int) (tried Java_org_sipdroid_codecs_G729_encode and Java_org_sipdroid_codecs_G729_encode___3SI_3BI)
                      at org.sipdroid.codecs.G729.encode(Native Method)
                      at org.sipdroid.media.RtpStreamSender.run(RtpStreamSender.java:475)
